on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # your build step here

      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@vmain
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-domain: 'hrtowii.nekoweb.org'
          nekoweb-username: 'hrtowii'
          # nekoweb-cookie: ${{ secrets.NEKOWEB_COOKIE }}
          nekoweb-folder: "dist"
          directory: "public"
